theme: jekyll-theme-minimal
paginate: 5
paginate_path: "/_posts/page:num/"
title: Of brain on cloud
description : Technical blog on AI,ML,Cloud and Software Engineering by Vinod Seshadri
github:
  is_project_page: false
site:
  is_user_page: false 
